# Generated by Django 3.1.5 on 2021-01-17 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 17, 6, 28, 15, 893564)),
        ),
    ]
